### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by harpavatkeerti** [marcobrando/Deep-Skin-Detection-on-Low-Resolution-Grayscale-Images#2]
Hi, really liked your work, as it is one of its kind, working for low resolution and grayscale images. I was interested in studying the output pattern's dependency on the resolution. So if you could provide the training code, it would be of great help, so that I can analyze the output while training iteration-by-iteration.
Thanks in advance.

**Comment by marcobrando** [comment]
Hi thank you for the interest in our work.
Unfortunately since the training phase of our model is very complex (as you can see on the article) and it is composed by many consecutive stages using different networks and datasets, I cannot upload the code to github.
But keep an eye on this project since we are working on a much lighter and easy to train network for the same problem. 
When this new work will be published I will upload the new model (and training code) here.
Best regards,
Marco.
